/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://maven.pkg.github.com/OWNER/REPOSITORY")
    }

    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }
}

dependencies {
    implementation("com.j256.ormlite:ormlite-jdbc:5.3")
    implementation("mysql:mysql-connector-java:8.0.26")
    implementation("org.projectlombok:lombok:1.18.22")
    annotationProcessor("org.projectlombok:lombok:1.18.22")
    implementation("com.googlecode.json-simple:json-simple:1.1.1")
    implementation("com.j256.ormlite:ormlite-core:5.3")
    compileOnly("org.bukkit:bukkit:1.12-R0.1-SNAPSHOT")
}

group = "de.coins.chaos"
version = "1.0"
description = "FreezeCoins"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
